version: '3.6'
services:
  postgresql:
    image: postgres:11.2
    # volumes:
    #   - db-data:/var/lib/postgres/data
    # container_name: dashboard-crawler
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'conduit-development'
    volumes:
      - ../postgres:/var/lib/postgresql/data
